### ISSUE TITLE
Send volunteers without UNSC not working

### ISSUE THREAD

**Issue by Mcboat** [PlayerHOI/cwm_developer_version#112]
Completing the focus to send volunteers to China without UNSC Authorization in US tree doesn't allow you to actually send the volunteers to china

**Comment by PlayerHOI** [comment]
Will take a look

**Comment by PlayerHOI** [comment]
@Mcboat - Works fine on my end, please make sure that other conditions for volunteers apply (like China having at least 10% surrender progress). If you encounter the issue again please attach a save game so that I can take another look.
