### ISSUE TITLE
disarmed nation gives more recruitable population than volunteer only

### ISSUE THREAD

**Issue by RootinPutin8** [PlayerHOI/cwm_developer_version#119]

**Comment by PlayerHOI** [comment]
Lets not open issues on WIP, only once work has been marked as finished by Mcboat we can start opening issues + if there are multiple issues concerning the same focus tree please open one issue and use tasks instead of opening an individual issue for each problem.

**Comment by PlayerHOI** [comment]
@RootinPutin8 - Please specify which idea you mean, enforced_disarnament  doesn't have any bonuses to recruitment.

**Comment by RootinPutin8** [comment]
im talking about the conscription law. volunteer only gives 0.4% recruitable population while disarmed nation gives 1.0%
