### ISSUE TITLE
(French Tree 40s) Autonomous Cameroon lacks proper flag and potential leader

### ISSUE THREAD

**Issue by Afrandez** [PlayerHOI/cwm_developer_version#124]
Assuming due to the ruling Imperialism ideology, Finding relative information and material should be able to fix the issue.
No issues for independent Cameroon

**Comment by PlayerHOI** [comment]
@Afrandez - Apparently the Cameroon war was in 50's so nor relevant for now.
My bad, will let you know when testing Cameroon is relevant.
Closing.
