### ISSUE TITLE
indonesian communist portrait is wrong

### ISSUE THREAD

**Issue by RootinPutin8** [PlayerHOI/cwm_developer_version#126]
![musso](https://user-images.githubusercontent.com/71093692/128752807-a137a487-1e26-4735-b4d8-425f9c6f39c8.jpg)

**Comment by PlayerHOI** [comment]
@RootinPutin8 What's his name? Can't really use this portrait...

**Comment by PlayerHOI** [comment]
Fixed by @RootinPutin8
