### ISSUE TITLE
African State Changes and Relevant Changes

### ISSUE THREAD

**Issue by GreatIanEmpire** [PlayerHOI/cwm_developer_version#128]
just an fyi to me and to everyone else about what needs to be done with those new African state changes. 

- [x] Malawi 
- [x] Tanzania 
- [x] Mozambique 
- [x] Uganda 
- [x] Djibouti 
- [x] Zimbabwe 
- [x] Botswana 
- [x] Zambia
- [x] Eritrea
- [x] Republic of the Congo
- [x] Gabon 
- [x] Central African Republic 
- [x] Chad 
- [x] Benin
- [x] Togo
- [x] Niger
- [x] Ghana,
- [x] Burkina Faso
- [x] Mali
- [x] Ivory Coast/Cote Ivoire
- [x] Liberia
- [x] Sierra Leone
- [x] Guinea
- [x] the Gambia
- [x] Senegal
- [x] Mauritania
- [x] Guinea-Bissau
- [x] 1 Province Nations (IE Burundi, Equatorial Guinea, Rwanda, @PlayerHOI )
- [x] Manpower rebalancing (@RootinPutin8 )
- [x] Relevant events (such as the Paris Peace Treaty, colonial wars, etc, for @PlayerHOI )

**Comment by PlayerHOI** [comment]
This is done.
