### ISSUE TITLE
Game crashes somehow related to German Occupation tree(?)

### ISSUE THREAD

**Issue by Afrandez** [PlayerHOI/cwm_developer_version#129]
I have literally no idea what might be causing this, but somehow being suspicious of German occupation tree due to occurrences somehow involving it (even while looking to the tree). I have updated local copy several times and this keeps happening, earliest after July 1948, while AI nations do German focuses.

If this is not just happening for me, this might be a serious problem, needs a review

**Comment by PlayerHOI** [comment]
@Afrandez Thanks for reporting, might be fixed in the latest update.
Let me know if you encounter this again.

**Comment by Afrandez** [comment]
UPDATE: found the issue; hovering cursor over some focuses causes the crash.
So far I found following focuses:
- Demilitarize the Rhineland
- Extend Authority to Ruhr
- Internationalize the Rhineland
- French Rhineland

**Comment by PlayerHOI** [comment]
That means you do not have all the required branches active, make sure you have the following branches active:
- Trunk/Master branch
- France branch
- Cultural Union branch
- Political Rework branch
- Africa Rework branch

**Comment by PlayerHOI** [comment]
Closing this one
