### ISSUE TITLE
Second Philippines civil war pops around 1953 in my game?

### ISSUE THREAD

**Issue by Mcboat** [PlayerHOI/cwm_developer_version#131]
I have no idea why this happened but I was playing as Vietnam and after I win the war, communists declared war on the Philippines again. I don't know if the second civil war is intended or not.

**Comment by PlayerHOI** [comment]
Thanks, will take a look.

**Comment by PlayerHOI** [comment]
Can anyone else confirm this? I could not replicate the issue...
@RootinPutin8 
@GreatIanEmpire 
@Afrandez

**Comment by PlayerHOI** [comment]
Confirmed to be result of PRC 1950's tree
