### ISSUE TITLE
(decolonization) Egypt is at war with some of countries declaring independence from UK

### ISSUE THREAD

**Issue by Afrandez** [PlayerHOI/cwm_developer_version#132]
Might be a similar case with Vietnamese war with Madagascar; so far they were at war with Uganda and British Somalia, Interestingly, other countries such as Kenya and Sierra Leone weren't at war with Egypt.

**Comment by PlayerHOI** [comment]
That would be the broken suez Crisis which I still need to rework, closing for now and we can take another look at this after the Suez Crisis has been reworked.
