### ISSUE TITLE
Timer for ending the vietnam war doesn appear

### ISSUE THREAD

**Issue by Mcboat** [PlayerHOI/cwm_developer_version#133]
In my AI game, Vietnam beat the french and pushed them out of Indochina but the timer to end the war doesn't appear. My theory is that it has something to do with the fact french took Saigon back and ended the timer but Vietnam retook it. I have even waited for a year.

**Comment by PlayerHOI** [comment]
Did the war eventually end? And what country were you playing?

**Comment by PlayerHOI** [comment]
@Mcboat - What country were you playing? France?

**Comment by Mcboat** [comment]
I wasn't able to recreate this bug in my few runs recently. So I'm closing this issue for now
