### ISSUE TITLE
(decolonization)Niger revolters spawned in impassable state (and without any notice)

### ISSUE THREAD

**Issue by Afrandez** [PlayerHOI/cwm_developer_version#135]
These states either should be defined to not eligible for revolts or reworked to be any other normal states.
See the attached picture:
![hoi4_92](https://user-images.githubusercontent.com/78501071/129072094-7e729180-a997-4ffa-adda-111ab2f08fc0.png)

**Comment by PlayerHOI** [comment]
Thanks, will try to find a solution to do but it's a flaw with the base game as well...

**Comment by PlayerHOI** [comment]
And what do you mean wihout notice? Wasn't there resistance in the state?

**Comment by Afrandez** [comment]
more than 80%. idk if this is a base game feature; but even with that it wouldn't make sense to have revolt in impassable states
