### ISSUE TITLE
PRC gets non Manchuria territory if KMT beats them at civil war

### ISSUE THREAD

**Issue by PlayerHOI** [PlayerHOI/cwm_developer_version#48]
A shown here:
https://youtu.be/G6UHKALMDX4?t=355

**Comment by Krafan** [comment]
I think this bug was fixed when China and PRC got 60's Focus Tree, ready to mark as done

**Comment by PlayerHOI** [comment]
Please confirm this no longer occurs.

**Comment by PlayerHOI** [comment]
Closed, no confirmations so far.
