### ISSUE TITLE
Korean War is Eternal

### ISSUE THREAD

**Issue by GreatIanEmpire** [PlayerHOI/cwm_developer_version#63]
Korean War does not end due to armistice event not triggering properly

**Comment by PlayerHOI** [comment]
Please provide a save game that allows to test this.

**Comment by PlayerHOI** [comment]
+ If this bug report is because of the stream on Twitch that RootinPutin had than you should have waited until 1953.7.27 for the ceasefire to trigger and you ended it at 1953.07.01

**Comment by PlayerHOI** [comment]
@RootinPutin8 - Any updates on this?

**Comment by PlayerHOI** [comment]
No update on this - closing
